name: sindikat_app
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: ">=3.3.4 <4.0.0"

dependencies:
  another_flushbar: ^1.12.30
  audioplayers: ^6.0.0
  cupertino_icons: ^1.0.6
  flutter:
    sdk: flutter
  flutter_blue_plus: ^1.32.8
  flutter_native_contact_picker: ^0.0.6
  flutter_phone_direct_caller: ^2.1.1
  flutter_sound: ^9.6.0
  flutter_svg: ^2.0.10+1
  geolocator: ^12.0.0
  get: 4.6.6
  get_storage: ^2.1.1
  http: ^1.2.1
  intl: ^0.19.0
  lottie: ^3.1.2
  path: ^1.9.0
  path_provider: ^2.1.3
  permission_handler: ^11.3.1
  phone_state: ^1.0.4
  speech_to_text: ^6.6.0
  string_extensions: ^0.7.2
  transitioned_indexed_stack: ^1.0.2
  url_launcher: ^6.3.0
  volume_controller: ^2.0.7

dev_dependencies:
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
    - assets/icons/
    - assets/models/
    - assets/lottie/
    - assets/audios/
